### ISSUE TITLE
Plant sampling protocol and weather data

### ISSUE THREAD

**Issue by Thioro18** [TREC-Agroecology/agroecosystems#12]
- Date 50% Emergence
- Biweekly sampling of stem height and diameter, and leaf chlorophyll
      When should we start measuring? 
      What distance from the soil for stem diameter?
      What time of the day?
      Same 10 plants or random?
- Biomass collected at harvest
- Weather data
     Weekly, biweekly, or monthly?

**Comment by Thioro18** [comment]
![echo](https://user-images.githubusercontent.com/31212467/40128104-d77b28b6-58fe-11e8-8742-05370cfa0384.jpg)

**Comment by brymz** [comment]
> - Date 50% Emergence

I think we have settled on a protocol here. It sounds like Thioro, Daniel, and Nikki had good success, yesterday.

> - Biweekly sampling of stem height and diameter, and leaf chlorophyll
>    - When should we start measuring?
>    - What distance from the soil for stem diameter?
>    - What time of the day?
>    - Same 10 plants or random?

- ASAP (within reason). Thioro and I talked about starting height biweekly at week 2. @readersm, that would be tomorrow. Diameter biweekly at week 4 and leaf chlorophyll weekly at week 8 or biweekly at week 4.
- At soil level.
- Anytime
- Random. Capture the variation in the population. Get the smallest, the biggest, and 8 in between.

> - Biomass collected at harvest

Has someone calculated when is 90 days for harvest? Let's get that on the calendar and make travel plans.

> - Weather data
>      Weekly, biweekly, or monthly?

The weather station will record at ~1 min intervals. We will need to download the data ~monthly.

**Comment by readersm** [comment]
Sounds great! I can collect height data tomorrow and schedule in my calendar the other collection dates. Do we want to take exactly 2 weeks out for the separate plots (Thursday for SP and Friday for AG) or can I take both of the plot's data the same day (I'd take both Friday in the future because I will have more help Friday mornings)? 

Our weather station is logging well (I had to fiddle with the battery a while ago) and I can download monthly data. If you ever do want to see it for some reason, here's the[ website link](https://www.rainwise.net/weather/echo33917).

For the Natural plot here, 90 days will be August 1st. And for the Ag plot, August 2nd.

**Comment by brymz** [comment]
> Do we want to take exactly 2 weeks out for the separate plots (Thursday for SP and Friday for AG) or can I take both of the plot's data the same day (I'd take both Friday in the future because I will have more help Friday mornings)?

Starting on Friday and every two weeks after that sounds good to me.
