### ISSUE TITLE
Last of the data collection

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#14]
Hi all! We were able to collect plant count on Friday last week. The SP plot was pretty low as was expected to some extent. 

Plots | Sites | Species 1 | count (number) | Species 2 | count (number)
-- | -- | -- | -- | -- | --
145 | SP | SH | 1 | VB | 21
146 | SP | SS | 29 | VB | 20
147 | SP | SH | 1 | SS | 110
148 | SP | SS | 293 |   |  
149 | SP | VB | 44 |   |  
150 | SP | SH | 2 |   |  
151 | SP | SH | 7 | SS | 9
152 | SP | SS | 10 |   |  
153 | SP | SH | 2 | VB | 21
154 | SP | VB | 39 |   |  
155 | SP | SH | 0 |   |  
156 | SP | SS | 235 | VB | 21
157 | SP | SS | 45 |   |  
158 | SP | SH | 13 | VB | 19
159 | SP | SS | 42 | VB | 17
160 | SP | SH | 5 |   |  
161 | SP | SH | 8 | SS | 44
162 | SP | VB | 44 |   |  
163 | SP | VB | 38 |   |  
164 | SP | SH | 6 |   |  
165 | SP | SS | 63 |   |  
166 | SP | SH | 2 | VB | 24
167 | SP | SS | 11 | VB | 21
168 | SP | SH | 5 | SS | 25
169 | SP | SH | 0 |   |  
170 | SP | SH | 7 | SS | 2
171 | SP | VB | 40 |   |  
172 | SP | SS | 43 | VB | 22
173 | SP | SH | 5 | VB | 21
174 | SP | SS | 19 |   |  
175 | SP | SS | 152 | VB | 19
176 | SP | VB | 41 |   |  
177 | SP | SH | 1 |   |  
178 | SP | SH | 8 | SS | 152
179 | SP | SS | 95 |   |  
180 | SP | SH | 14 | VB | 23
181 | AG | SS | 555 |   |  
182 | AG | SH | 397 |   |  
183 | AG | SS | 397 | VB | 15
184 | AG | SH | 226 | VB | 13
185 | AG | SH | 206 | SS | 308
186 | AG | VB | 23 |   |  
187 | AG | SH | 295 |   |  
188 | AG | SH | 141 | SS | 255
189 | AG | SH | 148 | VB | 11
190 | AG | SS | 438 |   |  
191 | AG | VB | 38 |   |  
192 | AG | SS | 259 | VB | 15
193 | AG | SH | 185 | VB | 15
194 | AG | SS | 669 |   |  
195 | AG | VB | 26 |   |  
196 | AG | SS | 339 | VB | 13
197 | AG | SH | 291 |   |  
198 | AG | SH | 144 | SS | 290
199 | AG | SS | 343 | VB | 17
200 | AG | SH | 171 | VB | 16
201 | AG | SH | 137 | SS | 273
202 | AG | VB | 33 |   |  
203 | AG | SS | 569 |   |  
204 | AG | SH | 185 |   |  
205 | AG | VB | 27 |   |  
206 | AG | SS | 267 | VB | 21
207 | AG | SH | 329 |   |  
208 | AG | SH | 132 | SS | 254
209 | AG | SH | 209 | VB | 15
210 | AG | SS | 789 |   |  
211 | AG | SH | 162 | SS | 312
212 | AG | VB | 43 |   |  
213 | AG | SS | 613 |   |  
214 | AG | SH | 316 |   |  
215 | AG | SS | 289 | VB | 26
216 | AG | SH | 138 | VB | 11

This week I believe is the last of the height, diameter and CHL data, but most of (if not all) of the sorghum is flowering. Should I still take height data with a full flowering stand? I have in the past measurement been avoiding sampling from flowering individuals. There are too few of those now.

Also, What is the protocol for biomass harvest?

**Comment by Thioro18** [comment]
Hi Stacy! 
I don't think you need more measurements of HDC (height, diameter, and chl) data. I stopped last week since the plants in 2 of the sites are too tall for me to reach them and measure height or chlorophyll. Unless Dr. Brym wants the height of flowering sorghum, I don't see the relevance of taking those.

For harvest, please refer to "Agroecosystems Methods" in the wiki. It says:
pull plants from ground
separate cover crop from weeds
identify and separate species
dry (48 hrs, 60C), and weight
separate leaves, stem, root for each cover crop species
o	separate a subset of 10 roots for each cover crop species
measure total root length
scan root
dry cover crop biomass for 48 hours at 60C and weigh
