### ISSUE TITLE
2018 winter methods

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#16]
### Field Management
Prep: 2 x disc before sowing (second disc on 11/19) 
- ECHO mailed seeds, put orange fencing around SP plot

Sowing: 
- 30  lbs/acre for sorghum and sunn hemp
- mucuna 50 lbs/acre

**Irrigation: Need to figure out because it will be dry season**
_normally irrigate annuals 2-3 times a week at ECHO for 2-3 hours each irrigation event_

### Data collection:
Soil Samples: Bulk density, before sowing and after harvest
Emergence: 50% more anecdotal
CHL: biweekly

**Heights: biweekly**
- **perhaps small, tall, canopy at a population level - need to figure out**

**Diameters: maybe at harvest?**

Biomass: 3, ½ meter samples; roots, shoot, and weed biomass at 2 months from sowing

Dry biomass: for each species, dry in temperature regulated oven **what temp? for how long?** at 2 months from sowing

Plant count per subplot: before harvest

Drone photos: every two weeks

Harvest at 2 months

**Comment by readersm** [comment]
In determining if we need to take diameters more than once, I made these two scatter plots of height (cm) vs. diameter (mm) for an early season measurement and a late season measurement. We don't have access to SAS right now because we are changing the server we are using it on (to reduce costs), so I just threw them together in excel. I decided to do means (not medians) for each subplot. I will break them down by species if I have time tomorrow (hoping to).
![image](https://user-images.githubusercontent.com/36899811/47751802-24178c80-dc69-11e8-8a8c-904726072f2b.png)
![image](https://user-images.githubusercontent.com/36899811/47751819-28dc4080-dc69-11e8-94ce-739680cc6842.png)

**Comment by brymz** [comment]
That's the scatter that I would expect to see. We should do diameters at some point, but probably can't justify doing too many reps.

**Comment by Thioro18** [comment]
Field Observations for Winter CC seasons:

- [ ] Sunn Hemp emerged at 50% after 5 days in the HH and OC and 8 days in the VF and FO

- [ ] I have noticed that VB emerged faster than SS in all sites in this winter season compared to the summer one

- [ ] Plants are still small to see differences in height after 2 weeks. Should we start measuring it after 4 weeks so that we will have 03 height measurements by the end of the 2 months (Week 4, week 6, and week 8)?

- [ ] For week 2 and 3, I think the emergence should be enough to characterize differences in growth between the CC treatments. What do you think?

**Comment by readersm** [comment]
They were for all of them combined and all species. I need to block out time to separate by species and do it again. 

I will update emergence once the VB are up! they are still at less than 50% here
heights at 4 weeks sounds good to me although we will only have 3 sampling dates, 4 might be better to see clear trends? 

Same with CHL? 4 weeks?

**Comment by readersm** [comment]
Yesterday was my last 50% emergence date! They are as follows for each site
AG 50% emergence
- SH reached in 6 days, SS in 8 days and VB in 14 days

SP 50% emergence
- SH reached in 7 days, SS in 8 days and VB in 14 days

I think the VB was so slow because we had a prolonged cold snap (3 days) while it was germinating and it takes a while in our sandy soil for the seeds to fully imbibe

**Comment by Thioro18** [comment]
> They were for all of them combined and all species. I need to block out time to separate by species and do it again.
> 
> I will update emergence once the VB are up! they are still at less than 50% here
> heights at 4 weeks sounds good to me although we will only have 3 sampling dates, 4 might be better to see clear trends?
> 
> Same with CHL? 4 weeks?

Hi Stacy, 
The leaves were to small to take CHL so I think we can start measuring it on W4 to minimize errors.  I attempted to take the height on week 2 and for all species they were between 14 for SH and SS and 17 cm for VB. So that first data point W2 is not as important as the W3, W4, and W6

**Comment by Thioro18** [comment]
> Yesterday was my last 50% emergence date! They are as follows for each site
> AG 50% emergence
> 
> * SH reached in 6 days, SS in 8 days and VB in 14 days
> 
> SP 50% emergence
> 
> * SH reached in 7 days, SS in 8 days and VB in 14 days
> 
> I think the VB was so slow because we had a prolonged cold snap (3 days) while it was germinating and it takes a while in our sandy soil for the seeds to fully imbibe

I am glad to know the SP site is doing better that last time.

**Comment by brymz** [comment]
Good stuff, team. Keep up the conversation!

**Comment by Thioro18** [comment]
**11/30/2018:** Field Observations for Winter CC seasons
All species reached 50% emergence in the for sites except the SS in VF_SSVB row&col 1. We might have an intense weed pressure in the FO. They are growing within the subplots and between the alleys. Next week, we will decide whether the CC need hand weeding or if they will out-compete the weeds.

**Comment by Thioro18** [comment]
Sorry to hear that Stacy. Do you know what the burned looking leave  and stem tip in the VB is?

**Comment by brymz** [comment]
Very sad news. We'll chat in the new year about a plan for the summer. The choices are to work through the challenges of this experiment or try a new direction. I think the bigger question for me is how/can you transition from this natural area to agriculture? We generally seek positive benefits from natural areas (i.e., ecosystem function), but that is clearly not what we are seeing.

**Comment by readersm** [comment]
The SH in the AG plot is about to flower!
I just got heights this morning and am heading out to get CHL now for both plots. 
![flower buds on sh in ag](https://user-images.githubusercontent.com/36899811/50650285-078c1f00-0f4e-11e9-85bc-e414da45baed.jpg)
![flower buds sh in ag](https://user-images.githubusercontent.com/36899811/50650286-0824b580-0f4e-11e9-8869-fc78e06a36ff.jpg)

**Comment by Thioro18** [comment]
Hi Stacy, Happy New Year!

The SH here started flower last week. I will take my 3rd and last measurement next week. We will harvest the week of Jan 14.

**Comment by Thioro18** [comment]
Hi Stacy,
We are going to harvest on Monday Jan 14th. He is the procedure we would like to follow. Do you have any comment about it? If we made changes in the field for any technical reason, I will update it.

Harvest procedures and steps
Step 1: Place the quadrat in the subplot
Step 2: Pull out plants and weeds by hand
Step 3: Separate cover crop species and weeds
Step 4: Separate roots from leaves+stems
Step 5: Weight root, leaves+stems for each species
Step 6: Count the number of plants for each species
Step 7: Take a subsample of 200 to 500 g of root and leave+stem biomass
        7.a. Weight the paper bag first and write down its weight on it 
        7.b. Chop the biomass to fit in the paper bag
Step 8: Spread biomass evenly over sampled area
Step 9: Repeat steps 1-6 for a total of three samples in each subplot.
Step 10: Use hedge trimmer to cut and the remaining biomass in the subplot


Thank you
Thioro

**Comment by readersm** [comment]
Harvest procedures and steps: My questions are in _**italics and bolded**_ under steps I need clarification about. 
Step 1: Place the quadrat in the subplot
**_randomly? at the estimated average?_**
Step 2: Pull out plants and weeds by hand
Step 3: Separate cover crop species and weeds
Step 4: Separate roots from leaves+stems
**_only for cover crops, not weeds, correct?_**
Step 5: Weight root, leaves+stems for each species
Step 6: Count the number of plants for each species
Step 7: Take a subsample of 200 to 500 g of root and leave+stem biomass
**_we typically only take 3 subsamples per species. Are we taking subsamples for every plot? and if so, for each species? are we also taking weed samples (I think we should take at least 3)?_**
7.a. Weight the paper bag first and write down its weight on it
7.b. Chop the biomass to fit in the paper bag
Step 8: Spread biomass evenly over sampled area
Step 9: Repeat steps 1-6 for a total of three samples in each subplot.
**_this is going to take a lot longer, but I'm up for it! I should have some help. Are you doing this 1 week after final heights or same week of final heights? Next week is my 3rd and final height/CHL collection_**
Step 10: Use hedge trimmer to cut and the remaining biomass in the subplot

Also, I'm assuming that since we are taking plant count samples in this protocol, that we are no longer doing total plant count for the whole subplot?

**Comment by Thioro18** [comment]
Stacy,
I will get back to your questions as soon I finish chlorophyll measurements. I will take height tomorrow and that will be all for this season data collection. Harvest is next week Jan 14th.
Thioro

Sent from my iPhone

On Jan 10, 2019, at 1:34 PM, Stacy Reader <notifications@github.com<mailto:notifications@github.com>> wrote:


Harvest procedures and steps: My questions are in italics and bolded under steps I need clarification about.
Step 1: Place the quadrat in the subplot
randomly? at the estimated average?
Step 2: Pull out plants and weeds by hand
Step 3: Separate cover crop species and weeds
Step 4: Separate roots from leaves+stems
only for cover crops, not weeds, correct?
Step 5: Weight root, leaves+stems for each species
Step 6: Count the number of plants for each species
Step 7: Take a subsample of 200 to 500 g of root and leave+stem biomass
we typically only take 3 subsamples per species. Are we taking subsamples for every plot? and if so, for each species? are we also taking weed samples (I think we should take at least 3)?
7.a. Weight the paper bag first and write down its weight on it
7.b. Chop the biomass to fit in the paper bag
Step 8: Spread biomass evenly over sampled area
Step 9: Repeat steps 1-6 for a total of three samples in each subplot.
this is going to take a lot longer, but I'm up for it! I should have some help. Are you doing this 1 week after final heights or same week of final heights? Next week is my 3rd and final height/CHL collection
Step 10: Use hedge trimmer to cut and the remaining biomass in the subplot

Also, I'm assuming that since we are taking plant count samples in this protocol, that we are no longer doing total plant count for the whole subplot?

**Comment by Thioro18** [comment]
**Question 1**: randomly? at the estimated average?
I would not say random because we need to consider the area of the subplot that does not have plants. Here at TREC, there are few subplots where we missed 1 to 2 rows and sometimes the seeds were not distributed from the begin to the end of the row. As a result, there are some void areas. The 3 quadrats should be representative of the area occupied by plants within the subplot. 

**Question 2**: only for cover crops, not weeds, correct?
I include weeds in the spreadsheet (see below) just in case. I think we need to sample them in few plots
PlotID | PlotName | Quadrat  No | CropName | Leaves+Stems | Roots | Weeds | Stem counts |  

**Question 3**: we typically only take 3 subsamples per species. Are we taking subsamples for every plot? and if so, for each species? are we also taking weed samples (I think we should take at least 3)?
We are taking a subsample for each specie in each plot but does not have to be for each quadrat. To me the 03 quadrats are more about plant distribution/density. So we can subsample from only 1 of the 3 quadrats. 
If we are only looking for a conversion factor, we can subsample by treatment rather that subplot. Dr. Brym may have something to say about that.
I do not think that we will take weeds biomass but I would not mind if we do.

**Question 4**: : this is going to take a lot longer
It will be but we may come up with back up plan if necessary. The number of plant in each quadrat is more accurate than total count per subplot. SS has more seeds that SH and VB so different density.

**Comment by Thioro18** [comment]
Hi Stacy,

We took 3 subsamples of roots and leaves+stems for each species. For VB and SS roots, we collected in rows 1 & 2, 3 & 4, 5 & 6. For the leaves+stems, we collected 1 to 2 subplots to get enough biomass. We weighted weed biomass but did not take samples.  
Please let me know if you have more questions.
Have a great day

Step 1: Place the quadrat in the subplot
Step 2: Pull out plants and weeds by hand
Step 3: Separate cover crop species and weeds
Step 4: Separate roots from leaves+stems
Step 5: Weight root, leaves+stems for each species. Weight weed fresh biomass (we did not collect weed sample)
Step 6: Count the number of plants for each species
Step 7: Take a subsample of 200 to 500 g of root and leave+stem biomass
Step 8: Spread biomass evenly over sampled area
Step 9: Repeat steps 1-6 for a total of three samples in each subplot.
Step 10: Use hedge trimmer to cut and the remaining biomass in the subplot

**Comment by readersm** [comment]
Perfect! Got it! I'm going to print sheets now so we are ready to go on Tuesday! 

Planting another trial on Monday, but we should have ample time on Tuesday and Thursday/Friday to get both done :)

**Comment by Thioro18** [comment]
Hi Stacy,

I finish harvest Jan 17th. How did yours went?

**Comment by readersm** [comment]
Yep! harvest is all done here. I still need to make sure everything is dried down, but will let you know as soon as I have those dry biomass weights as well. I haven't had time to input any data from last week, but am hoping to early next week

**Comment by brymz** [comment]
Can we get these methods summarized/updated on https://github.com/TREC-Agroecology/agroecosystems/wiki/Agroecosystems-Methods? With that, we can close this issue.

**Comment by readersm** [comment]
Yes! I will work on it this afternoon and then close it. Sorry for the delay.

**Comment by readersm** [comment]
I just updated everything but still had one question Thioro, you can help me with
Are we still planning on taking soil samples before and after each season to measure OM or another Carbon measurement (mineralization or combustion)? I want to make sure it's on the methods list correctly

**Comment by Thioro18** [comment]
Hi Dr. Brym and Stacy, 

Sorry I missed your comments. Stacy, soil sampling before planting and at harvest was the plan but:
- According to Dr. Li, we see soil N and C difference 1 - 2 months after the biomass is incorporated in the soil. Since we do not measure tissue sample to evaluate the C and N contents of the biomass, taking soil sample after harvest will not give us lot of information. For this reason, he advised to only take sample before each planting. 
- Plowing the soil before planting by mixing all the treatments is another issue when measuring soil OM or other parameters because if there is an increase on SOM, we cannot tell which treatment (cover crop or mixture) causes that increase. With the first soil samples (May 2018), we can do any soil physical or chemical analysis.

**Comment by readersm** [comment]
Great, Thanks Thioro. That was the last question I had to be able to close up this issue and update the methods page. Please feel free to look over the methods page I made and correct anything I may have missed or misunderstood.
