### ISSUE TITLE
ECHO data analysis preliminary questions

### ISSUE THREAD

**Issue by readersm** [TREC-Agroecology/agroecosystems#19]
## ECHO Ag site data analysis preliminary questions
_Stacy: I'm still thinking through these, but wanted to get something started/moving along in my thought process! I will make sure to review these again on Monday!_ 
### Whole-plot Agroecosystem questions 
- Does proximity to Agricultural production system (East of Ag site) or bees (West of Ag site) effect treatment physiology or biomass (this would use column position, _column effect within trt_)
- Does proximity to natural ecosystem (North and South) effect treatment physiology or biomass  (this would use row position, _row effect within trt_)
- I am also curious if the distance from the Oak tree has any effect on the cover crop physiology. Is this measurable?
- Does proximity to Agricultural production system (East of Ag site) or bees (West of Ag site) effect weed biomass  (this would use column position, _column effect among trt_)
- Does proximity to natural ecosystem (North and South) effect weed biomass  (this would use row position, _row effect among trt_)

### Competition questions
- Does mixed cropping with mucuna effect sunn hemp or sorghum CHL, physiology, or biomass
- Does mixed cropping with sunn hemp effect sorghum or mucuna CHL, physiology, or biomass
- Does mixed cropping with sorghum effect mucuna or sunn hemp CHL, phsyiology, or biomass
- Do cover crop treatments differ in ability to effectively control weeds

### Production-based questions
- Do cover crop mixtures (in general) differ in biomass production (mass/area basis) compared to monocropped cover crops
- Do cover crop trts differ in overall biomass yield (mass/area basis) from one another
- Do specific cover crop mixtures differ in overall biomass yield compared to their solo constituents (pairwise?)

### Soil-based questions (I don't have this data, I think Thioro is working on it!) 
- Does pH effect cover crop CHL, physiology, or production
- Does OM effect over crop CHL, physiology, or production

**Comment by Thioro18** [comment]
> ## ECHO Ag site data analysis preliminary questions
> _Stacy: I'm still thinking through these, but wanted to get something started/moving along in my thought process! I will make sure to review these again on Monday!_
> 
> ### Whole-plot Agroecosystem questions
> * Does proximity to Agricultural production system (East of Ag site) or bees (West of Ag site) effect treatment physiology or biomass (this would use column position, _column effect within trt_)
> * Does proximity to natural ecosystem (North and South) effect treatment physiology or biomass  (this would use row position, _row effect within trt_)
> * I am also curious if the distance from the Oak tree has any effect on the cover crop physiology. Is this measurable? 
**Thioro:** I think you can measure the effect of oak tree based on its shading effect at different time of the day. You can identify the row (s) or column (s) that are shaded.
> * Does proximity to Agricultural production system (East of Ag site) or bees (West of Ag site) effect weed biomass  (this would use column position, _column effect among trt_)
> * Does proximity to natural ecosystem (North and South) effect weed biomass  (this would use row position, _row effect among trt_)
> 
> ### Competition questions
> * Does mixed cropping with mucuna effect sunn hemp or sorghum CHL, physiology, or biomass
> * Does mixed cropping with sunn hemp effect sorghum or mucuna CHL, physiology, or biomass
> * Does mixed cropping with sorghum effect mucuna or sunn hemp CHL, phsyiology, or biomass
> * Do cover crop treatments differ in ability to effectively control weeds
**Thioro:** When we chatted last year, I sent you a excel file with the computations of root and shoot LER to analysis the effects of mixture versus monoculture on biomass production for roots and shoots.
As I was looking at the TREC data 2 weeks ago, I think it will be helpful to estimate the percent cover within the quadrat for each treatment because it will help answer in part the question of the effectiveness of CC on weeds. In many papers I read, weed suppression was either via allelopathy or full ground cover from the CC.
> ### Production-based questions 
> * Do cover crop mixtures (in general) differ in biomass production (mass/area basis) compared to monocropped cover crops
> * Do cover crop trts differ in overall biomass yield (mass/area basis) from one another
> * Do specific cover crop mixtures differ in overall biomass yield compared to their solo constituents (pairwise?)
**Thioro:** I think these questions are highly related to the competitions questions unless I do not understand the context here.
> ### Soil-based questions (I don't have this data, I think Thioro is working on it!)
> * Does pH effect cover crop CHL, physiology, or production
> * Does OM effect over crop CHL, physiology, or production
**Thioro:** If you have access on the shared drive, you can find the soil data there. Otherwise I will email them to you. If you feel comfortable with you pH data from ECHO, please use them because I do not have pH data. I measured the SOM and Total P for your soil as well and you will have them by the end of this week. If the bags of your soil samples are not open to dry, please do so because some of them were still humid and I could not do the OM last Tuesday. By now, they should be dry enough so I will be working on that this afternoon.
For the soil bulk density, you can refer to the short video I sent you. You can measure it before the till the soil (1 to 2 weeks before planting). The challenge you may have is the sandy nature of the soil because when you lift up the can, you should not lose soil from it and most of the time it is the case with sandy soil. You should not wet the soil either which makes is more challenging. However, you can measure BD early in the morning before the soil dries completely. The moisture level in the morning is acceptable because the soil is not saturated.
We have not chat this semester yet but we can schedule on Thursday mornings. Also, please let me know if there is something I miss in your questions.

**Comment by readersm** [comment]
The competition questions are more about if they negatively impact one another when mixed
biomass, I'm thinking do we actually get a boost in biomass by mixed cropping compared to solo cropping.
Yes, I have the spreadsheet that you sent for the LER! Very helpful, thank you!
I don't feel comfortable with my pH meter (we need a new probe) because I was having to recalibrate it every few hours, meaning it was off :(

**Comment by Thioro18** [comment]
> The competition questions are more about if they negatively impact one another when mixed
> biomass, I'm thinking do we actually get a boost in biomass by mixed cropping compared to solo cropping.
> Yes, I have the spreadsheet that you sent for the LER! Very helpful, thank you!
> I don't feel comfortable with my pH meter (we need a new probe) because I was having to recalibrate it every few hours, meaning it was off :(

There is an equation for plant competition that Dr. Brym explained to me last year. If you have all the different factors to account for, it will be helpful.
For the pH meter, we have the same problem in the soil lab here. To have an idea about the soil pH, you can use it but you cannot publish the data because the meter is not accurate. Unfortunately, the pH meter from another lab is not functioning at all. Yes, we do need a new probe.

**Comment by brymz** [comment]
> more about if they negatively impact one another when mixed
biomass

We should expect a "boost in biomass" with mixed cropping, but the expectation for mixed species would actually be a relaxation in "negative impacts". The competition equation Thioro is referring to is called Lotka-Voltera ([Link](https://en.wikipedia.org/wiki/Competitive_Lotka%E2%80%93Volterra_equations)). That theory suggests individuals that are more similar will experience greater competition. So, individuals of the same species ("intraspecific") will have greater competition than individuals from different species ("interspecific").

**Comment by readersm** [comment]
@Danielcalza here is also a conversation Thioro, Zack and I had a while back. Just to keep you in the loop.
